#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ibus-table
Version  : 1.9.14
Release  : 7
URL      : http://mfabian.fedorapeople.org/ibus-table/ibus-table-1.9.14.tar.gz
Source0  : http://mfabian.fedorapeople.org/ibus-table/ibus-table-1.9.14.tar.gz
Summary  : The Table engine for IBus platform
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: ibus-table-bin = %{version}-%{release}
Requires: ibus-table-data = %{version}-%{release}
Requires: ibus-table-libexec = %{version}-%{release}
Requires: ibus-table-license = %{version}-%{release}
Requires: ibus-table-locales = %{version}-%{release}
Requires: ibus-table-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(ibus-1.0)

%description
The package contains general Table engine for IBus platform.

%package bin
Summary: bin components for the ibus-table package.
Group: Binaries
Requires: ibus-table-data = %{version}-%{release}
Requires: ibus-table-libexec = %{version}-%{release}
Requires: ibus-table-license = %{version}-%{release}

%description bin
bin components for the ibus-table package.


%package data
Summary: data components for the ibus-table package.
Group: Data

%description data
data components for the ibus-table package.


%package dev
Summary: dev components for the ibus-table package.
Group: Development
Requires: ibus-table-bin = %{version}-%{release}
Requires: ibus-table-data = %{version}-%{release}
Provides: ibus-table-devel = %{version}-%{release}
Requires: ibus-table = %{version}-%{release}

%description dev
dev components for the ibus-table package.


%package libexec
Summary: libexec components for the ibus-table package.
Group: Default
Requires: ibus-table-license = %{version}-%{release}

%description libexec
libexec components for the ibus-table package.


%package license
Summary: license components for the ibus-table package.
Group: Default

%description license
license components for the ibus-table package.


%package locales
Summary: locales components for the ibus-table package.
Group: Default

%description locales
locales components for the ibus-table package.


%package man
Summary: man components for the ibus-table package.
Group: Default

%description man
man components for the ibus-table package.


%prep
%setup -q -n ibus-table-1.9.14
cd %{_builddir}/ibus-table-1.9.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604095469
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604095469
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus-table
cp %{_builddir}/ibus-table-1.9.14/COPYING %{buildroot}/usr/share/package-licenses/ibus-table/caeb68c46fa36651acf592771d09de7937926bb3
%make_install
%find_lang ibus-table

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ibus-table-createdb

%files data
%defattr(-,root,root,-)
/usr/share/appdata/ibus-table.appdata.xml
/usr/share/applications/ibus-setup-table.desktop
/usr/share/ibus-table/data/pinyin_table.txt.bz2
/usr/share/ibus-table/engine/chinese_variants.py
/usr/share/ibus-table/engine/factory.py
/usr/share/ibus-table/engine/ibus_table_location.py
/usr/share/ibus-table/engine/main.py
/usr/share/ibus-table/engine/tabcreatedb.py
/usr/share/ibus-table/engine/table.py
/usr/share/ibus-table/engine/tabsqlitedb.py
/usr/share/ibus-table/icons/acommit.svg
/usr/share/ibus-table/icons/cb-mode.svg
/usr/share/ibus-table/icons/chinese.svg
/usr/share/ibus-table/icons/english.svg
/usr/share/ibus-table/icons/full-letter.svg
/usr/share/ibus-table/icons/full-punct.svg
/usr/share/ibus-table/icons/half-letter.svg
/usr/share/ibus-table/icons/half-punct.svg
/usr/share/ibus-table/icons/ibus-table.svg
/usr/share/ibus-table/icons/ncommit.svg
/usr/share/ibus-table/icons/onechar.svg
/usr/share/ibus-table/icons/phrase.svg
/usr/share/ibus-table/icons/py-mode.svg
/usr/share/ibus-table/icons/sc-mode.svg
/usr/share/ibus-table/icons/scb-mode.svg
/usr/share/ibus-table/icons/tab-mode.svg
/usr/share/ibus-table/icons/tc-mode.svg
/usr/share/ibus-table/icons/tcb-mode.svg
/usr/share/ibus-table/setup/ibus-table-preferences.ui
/usr/share/ibus-table/setup/main.py
/usr/share/ibus-table/setup/version.py
/usr/share/ibus-table/tables/template.txt
/usr/share/ibus/component/table.xml

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/ibus-table.pc

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ibus-engine-table
/usr/libexec/ibus-setup-table

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ibus-table/caeb68c46fa36651acf592771d09de7937926bb3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ibus-table-createdb.1

%files locales -f ibus-table.lang
%defattr(-,root,root,-)

